# Generated by Django 5.2.6 on 2025-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('nivel', models.CharField(max_length=50)),
                ('q1', models.CharField(max_length=50)),
                ('q2', models.CharField(max_length=50)),
                ('q3', models.CharField(max_length=50)),
                ('q4', models.CharField(max_length=50)),
                ('q5', models.CharField(max_length=50)),
                ('perfil_obtenido', models.CharField(max_length=100)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('cursos_interes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
